### ISSUE TITLE
Add support for custom path

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-model-generator#1]
Add support for custom path

```
Point:
  path: graph/detail
  type: object
  required:
    - d
    - value
  properties:
    d:
      type: string
      format: date
    value:
      type: number
    valuePct:
      type: number
    min:
      type: number
    minPct:
      type: number
    max:
      type: number
    maxPct:
      type: number
```
