### ISSUE TITLE
Add option to ignore a field for locale usage

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-model-generator#11]
Use the options below. This way this tool can be used by everybody.
```
User:
  properties:
    firstName:
       type: String
    isFavourite:
       ignore: true
       type: bool
```
