### ISSUE TITLE
Make the type detector even smarter

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-model-generator#124]
```
Project:
  path: webservice/projects
  equals_and_hash_code: false
  properties:
    projectId: int
    name: String
    apiKey: String?
    activated: bool
    locales:
      type: array
      items:
        type: WritorLocale
      required: false
      include_if_null: false
```

could be this:
```
Project:
  path: webservice/projects
  equals_and_hash_code: false
  properties:
    projectId: int
    name: String
    apiKey: String?
    activated: bool
    locales:
      type: List<WritorLocale>?
      include_if_null: false
```

because `include_if_null:false `was added it is not possible to use `List<WritorLocale>?` anymore
