### ISSUE TITLE
Have tests also validate config.txt

### ISSUE THREAD

**Issue by ikbendewilliam** [icapps/flutter-model-generator#126]
The config.txt is not read in a test. This seems like an oversight?

Example Unknown enum value:
Config:
```yaml
Person:
  path: user/person/
  type: object
  properties:
    firstName:
      required: false
      include_if_null: false
      type: string
Gender:
  path: user/person/
  type: enum
  properties:
    MALE:
    FEMALE:
    X:
```

Test:
```dart
    test('Normal ObjectModelWriter with do not includeIfNull', () {
      final model = ObjectModel(
        name: 'Person',
        path: 'path_to_my_model',
        baseDirectory: 'base_dir',
        generateForGenerics: false,
        staticCreate: false,
        fields: [
          Field(
            name: 'gender',
            type: ObjectType('Gender'),
            isRequired: true,
            ignore: false,
            includeIfNull: true,
            nonFinal: false,
            unknownEnumValue: 'X',
            ignoreEquality: false,
          ),
        ],
        converters: [],
      );
      WriterTestHelper.testObjectModelWriter(model, [], 'unknown-enum-value');
    });
```

Either we use `final model = ObjectModel(` and remove the `config.txt` or we use the `config.txt`.
