### ISSUE TITLE
Custom fields on enum

### ISSUE THREAD

**Issue by ikbendewilliam** [icapps/flutter-model-generator#130]
It would be nice if we can add values to the enum's. Like this for example:

```yaml
AgeRange:
  path: webservice/user
  type: enum
  properties:
    child:
      startAge: 0
      endAge: 10
    teen:
      startAge: 10
      endAge: 20
    youngAdult:
      startAge: 20
      endAge: 30
```

The generator would be smart enough to see that startAge and endAge are custom fields. 
TBD how we can add default values for these fields
