### ISSUE TITLE
Support lists in map

### ISSUE THREAD

**Issue by jorre127** [icapps/flutter-model-generator#135]
It would be nice if we could support list in maps like:

```
Chat:
  path: webservice/chat
  properties:
    name: String
    id: String
    unreadMessages: Map<String, List<String>>
```
