### ISSUE TITLE
Empty properties should be supprted

### ISSUE THREAD

**Issue by NicolaVerbeeck** [icapps/flutter-model-generator#136]
Currently the following is not supported:

```yaml
DigitalOutNode:
  extends: IdNode
  properties:
```
