### ISSUE TITLE
test_Test will result in test_test

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-model-generator#14]
This should be supported
```
    test_Test:
      required: true
      type: string
    some_Thing:
      required: true
      type: string
    some_ThinG_huGE:
      required: true
      type: string
```
