### ISSUE TITLE
path ending with a / is currently not supported. 

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-model-generator#17]
Crash when the app is started back up
```
#################################################################################
#####                                TODO                                    #####
##################################################################################
Todo:
  path: webservice/todo/
  properties:
```
