### ISSUE TITLE
Use totally custom path for models

### ISSUE THREAD

**Issue by JeremiFerre** [icapps/flutter-model-generator#31]
Hello,

By default, models are generated in the directory lib/model, even with a custom path.

```yaml
UserModel:
  path: webservice/user
  properties:
    id:
      type: int
```

It would be nice to be able to specify a really custom path to generate for example in lib/src/models.

Thank you and have a good day.
