### ISSUE TITLE
Support nested generics

### ISSUE THREAD

**Issue by NicolaVerbeeck** [icapps/flutter-model-generator#76]
Support nested generics inside the top level array/map declaration.
Eg:
```yaml
SomeObject:
  properties:
    someMap:
        type: map
        items:
          key: String
          value: List<int>
```
